AWSTemplateFormatVersion: '2010-09-09-OC'
Description: default template generated for organization with master account 208334959160

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: Roman Naumenko
      AccountId: '208334959160'
      RootEmail: roman.naumenko@bestroman.com
      Alias: portalocean

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole
      ServiceControlPolicies: !Ref RestrictUnusedRegionsSCP

  SharedAccountsOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared-accounts
      Accounts: !Ref CicdAccountForBuildsAndDeploymentsAccount

  ApplicationxAccountsOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: applicationx-accounts
      Accounts:
        - !Ref ApplicationXDevelopmentAccount
        - !Ref ApplicationXProductionAccount

  ApplicationXDevelopmentAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Application X development account
      AccountId: '793106133212'
      RootEmail: roman+appx-dev@naumenko.ca
      Alias: naumenko-appx-dev
      Tags:
        subdomain: appx-dev
        budget-alarm-threshold: '5'
        account-owner-email: a+appx-dev@naumenko.ca

  ApplicationXProductionAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: Application X production account
      AccountId: '121722331275'
      RootEmail: roman+appx-prod@naumenko.ca
      Alias: naumenko-appx-prod
      Tags:
        budget-alarm-threshold: '5'
        account-owner-email: a+appx-prod@naumenko.ca

  CicdAccountForBuildsAndDeploymentsAccount:
    Type: OC::ORG::Account
    Properties:
      AccountName: CICD account for builds and deployments
      AccountId: '748368682614'
      RootEmail: roman+shared-cicd@naumenko.ca
      Alias: naumenko-cicd
      Tags:
        budget-alarm-threshold: '5'
        account-owner-email: a+shared-cicd@naumenko.ca

  RestrictUnusedRegionsSCP:
    Type: OC::ORG::ServiceControlPolicy
    Properties:
      PolicyName: RestrictUnusedRegions
      Description: Restrict Unused regions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnsupportedRegions
            Effect: Deny
            NotAction:
              - 'cloudfront:*'
              - 'iam:*'
              - 'route53:*'
              - 'support:*'
            Resource: '*'
            Condition:
              StringNotEquals:
                'aws:RequestedRegion':
                  - us-east-1
                  - us-east-2
        

